# Generated by Django 5.1.2 on 2024-10-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('trophy', 'Trophy'), ('memento', 'Memento')], max_length=10, unique=True),
        ),
    ]
